/*
 * Copyright 2010 ALM Works Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.almworks.sqlite4java;

/**
 * Although this class was not generated by SWIG, we'll keep the naming for convenience
 *
 * @author Igor Sereda
 */
class SWIGTYPE_p_direct_buffer {
  private long swigCPtr;

  protected SWIGTYPE_p_direct_buffer(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_direct_buffer() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_direct_buffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}