package io.github.getsixtyfour.openpyn.map

import com.naver.android.svc.core.screen.SvcFragment

/**
 * Generated by SVC processor. (https://github.com/naver/svc). Don't change this class.
 */
abstract class AbstractMapFragment : SvcFragment() {

    val views: MapViews
        get() = baseViews as MapViews
    val controlTower: MapControlTower
        get() = baseControlTower as MapControlTower

    override fun createViews(): MapViews = MapViews()

    override fun createControlTower(): MapControlTower = MapControlTower()
}
