package io.github.getsixtyfour.openpyn.map

import com.naver.android.svc.core.controltower.ControlTower

/**
 * Generated by SVC processor. (https://github.com/naver/svc). Don't change this class.
 */
abstract class AbstractMapControlTower : ControlTower() {
    open val screen: MapFragment
        get() = baseScreen as MapFragment

    open val views: MapViews
        get() = baseViews as MapViews
}
